SongList/Models/ErrorViewModel.cs
namespace SongList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SongList/Models/Genre.cs
namespace SongList.Models
{
    public class Genre
    {
        public string GenreId { get; set; }
        public string Name { get; set; }
    }
}

SongList/Models/Song.cs
using System.ComponentModel.DataAnnotations;

namespace SongList.Models
{
    public class Song
    {
        public int SongId { get; set; }

        [Required(ErrorMessage = "Please enter song name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a year")]
        [Range(1900, 2021, ErrorMessage = "Year must be between 1900 and 2021")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Please enter the rating")]
        [Range(1, 5, ErrorMessage = "Rating must be between 1 and 5")]
        public int? Rating { get; set; }


        [Required(ErrorMessage = "Please enter genre")]
        public string GenreId { get; set; }
        public Genre Genre { get; set; }


        public string Slug => Name?.Replace (' ','-').ToLower() + '-' + Year?.ToString();


    }
}

SongList/Models/SongContext.cs
using Microsoft.EntityFrameworkCore;

namespace SongList.Models
{
    public class SongContext : DbContext
    {
        public SongContext(DbContextOptions<SongContext> options)
          : base(options)
        {
        }

        public DbSet<Song> Songs { get; set; }
        public DbSet<Genre> Genres { get; set; }
       

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Genre>().HasData(
                 new Genre { GenreId = "M", Name = "Metal" },
                 new Genre { GenreId = "R", Name = "Rap" },
                 new Genre { GenreId = "H", Name = "Hip Hop" },
                 new Genre { GenreId = "RC", Name = "Rock" }
                  );


            modelBuilder.Entity<Song>().HasData(
              new Song
              {
                  SongId = 1,
                  Name = "Master of Puppets",
                  Year = 1980,
                  Rating = 5,
                  GenreId = "M"
              },
              new Song
              {
                  SongId = 2,
                  Name = "Wonderwall",
                  Year = 1990,
                  Rating = 4,
                  GenreId = "RC"

              },
              new Song
              {
                  SongId = 3,
                  Name = "Lose Yourself",
                  Year = 2005,
                  Rating = 1,
                  GenreId = "R"

              });
        }
    }
}

SongList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SongList.Models;


namespace SongList.Controllers
{
    public class HomeController : Controller
    {
        private SongContext context { get; set; }

        public HomeController(SongContext ctx)
        {
            context = ctx;
        }
       
        public IActionResult Index()
        {
            var songs = context.Songs.Include(m => m.Genre).OrderBy(m => m.Name).ToList();
            return View(songs);
        }

    }
}

SongList/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using SongList.Models;

namespace SongsList.Controllers
{
    public class SongController : Controller
    {
        private SongContext context { get; set; }

        public SongController(SongContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
           ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();
            return View("Edit", new Song());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();
            var song = context.Songs.Find(id);
            return View(song);
        }

        [HttpPost]
        public IActionResult Edit(Song song)
        {
            if (ModelState.IsValid)
            {
                if (song.SongId == 0)
                    context.Songs.Add(song);
                else
                    context.Songs.Update(song);

                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = song.SongId == 0 ? "Add" : "Edit";
                ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();

                return View(song);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var song = context.Songs.Find(id);
            return View(song);
        }

        [HttpPost]
        public IActionResult Delete(Song song)
        {
            context.Songs.Remove(song);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

SongList/Views/Home/Index.cshtml
@model List<Song>
@{ 
  ViewBag.Title = "My Songs";
}

<a asp-controller="Song" asp-action="Add">Add new song</a>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Genre</th>
      <th>Rating</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var song in Model)
    {
      <tr>
        <td>@song.Name</td>
        <td>@song.Year</td>
        <td>@song.Genre.Name</td>
        <td>@song.Rating</td>
        <td>
          <a asp-controller="Song" asp-action="Edit" asp-route-id="@song.SongId" asp-route-slug="@song.Slug">Edit</a>
          <a asp-controller="Song" asp-action="Delete" asp-route-id="@song.SongId" asp-route-slug="@song.Slug">Delete</a>
        </td>
      </tr>
    }
  </tbody>
</table>

SongList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SongList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SongList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SongList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SongList 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SongList/Views/Song/Delete.cshtml
@model Song

@{ 
  ViewBag.Title = "Delete Song";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Name @Model.Year</h3>

<form asp-action="Delete" method="post">
  <input type="hidden" asp-for="SongId" />

  <button type="submit" class="btn btn-primary">Delete</button>
  <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

SongList/Views/Song/Edit.cshtml
@model Song
@{ 
  ViewBag.Title = ViewBag.Action + " song";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Edit" method="post">


  <div class="form-group">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" class="form-control" />
  </div>

  <div class="form-group">
    <label asp-for="Year">Year</label>
    <input asp-for="Year" class="form-control" />
  </div>

  <div class="form-group">
    <label asp-for="GenreId">Genre</label>
    <select asp-for="GenreId" class="form-control">
      <option value="">Select a Genre</option>
      @foreach (Genre genre in ViewBag.Genres)
      {
        <option value="@genre.GenreId">@genre.Name</option>
      }
        </select>
  </div>

  <div class="form-group">
    <label asp-for="Rating">Rating</label>
    <input asp-for="Rating" class="form-control" />
  </div>

  <input type="hidden" asp-for="SongId" />

  <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
  <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>